version: '3.8'

services:
  sentinel-backend:
    build: 
      context: ./sentinel-backend
      dockerfile: Dockerfile
    container_name: sentinel_backend
    ports:
      - "8000:8000"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./sentinel-backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_HOST=tcp://host.docker.internal:2375
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  sentinel-frontend:
    build:
      context: ./sentinel-frontend
      dockerfile: Dockerfile
    container_name: sentinel_frontend
    ports:
      - "3001:5173"
    volumes:
      - ./sentinel-frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - sentinel-backend
